Fix cmake build path
On Travis-CI the build fails with:
  $ cmake --build ..
  Error: could not load cache

This is because the path for the --build command should be . (i.e.
the build directory) rather than .. (the source directory).

Tests:
 - Manually run the cmake commands in the script in my
   development directory and check the build works as it should.